apiVersion: v1
kind: Secret
metadata: 
    name: application-secret
type: Opaque
data:
   REDIS_PASSWORD: U2VjcmV0MTIzCg==
   DB_PASSWORD: U2VjcmV0MTIzCg==
   APP_KEY: YmFzZTY0OlYweEFXc3JjeUFQTVkxK2tneXNBV20ycHRWU0ExMStVQXU3OG8vTXFEakk9Cg==
