version: "3"
services:
    backend:
        image: cehamot/backend-appoinmentapp:1
        ports:
            - "9000:9000"
        depends_on:
            - database
        networks:
            - my_network
        environment:
            - APP_KEY="base64:+JPQ+hF+atVJWZwt5IFumEWwWJbKXctGMBdCe380PDw="
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_PORT=3306
            - DB_HOST=database
            - DB_DATABASE=db_appointmentapp
            - DB_USERNAME=dani
            - DB_PASSWORD=secret123

    frontend:
        image: cehamot/frontend-appoinmentapp:4
        ports:
            - "3100:80"
        depends_on:
            - backend
        networks:
            - my_network

    database:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: db_appointmentapp
            MYSQL_USER: dani
            MYSQL_PASSWORD: secret123
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - my_network

networks:
    my_network:
        driver: bridge

volumes:
    mysql_data:
