name: Docker Image Backend CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_TOKEN}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
      - name: Get repository release tag
        id: timeseries
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          excludes: prerelease, draft
          repository: ${{ github.repository }}
      - name: Build Docker image
        run: |
          docker build . -f docker/fpm.Dockerfile-t ${{secrets.DOCKER_USERNAME}}/backend-appoinmentapp:${{ steps.timeseries.outputs.release }} .
      - name: Docker push image
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/backend-appoinmentapp:${{ steps.timeseries.outputs.release }}